"""change executor field to user_id

Revision ID: 443d37581e66
Revises: eed3cb6d5b98
Create Date: 2025-05-19 20:34:56.096688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '443d37581e66'
down_revision: Union[str, None] = 'eed3cb6d5b98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executor', sa.Column('user_id', sa.UUID(), nullable=False))
    op.drop_index('ix_executor_executor_id', table_name='executor')
    op.create_index(op.f('ix_executor_user_id'), 'executor', ['user_id'], unique=False)
    op.drop_constraint('executor_executor_id_fkey', 'executor', type_='foreignkey')
    op.create_foreign_key(None, 'executor', 'local_user', ['user_id'], ['id'])
    op.drop_column('executor', 'executor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executor', sa.Column('executor_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'executor', type_='foreignkey')
    op.create_foreign_key('executor_executor_id_fkey', 'executor', 'local_user', ['executor_id'], ['id'])
    op.drop_index(op.f('ix_executor_user_id'), table_name='executor')
    op.create_index('ix_executor_executor_id', 'executor', ['executor_id'], unique=False)
    op.drop_column('executor', 'user_id')
    # ### end Alembic commands ###
