http:
  middlewares:
    cors:
      headers:
        accessControlAllowOriginListRegex: "^https?://[a-zA-Z0-9.-]+(:[0-9]+)?$"
        accessControlAllowMethods: "GET,OPTIONS,PUT,POST,DELETE"
        accessControlAllowHeaders: "Authorization,Content-Type"
        accessControlAllowCredentials: true
        addVaryHeader: true

    strip-auth-header:
      headers:
        customRequestHeaders:
          Authorization: ""

    oauth-auth:
      forwardAuth:
        address: "http://oauth2-proxy:4180/oauth2/auth"
        # address: "http://debug-proxy:80"
        trustForwardHeader: true
        authResponseHeaders:
          - "X-Auth-Request-User"
          - "X-Auth-Request-Email"
          - "X-Auth-Request-Groups"

    auth-chain:
      chain:
        middlewares:
          - oauth-auth
          - strip-auth-header
        
